"""Real PDF generation for the demo (fpdf2). The seed script and CSV bulk
issuance produce genuine certificate PDFs, not placeholders: they contain
issuer, student, title, date and a credential id, so the Evidence Agent has
real text to extract and the hash anchored on-chain is a real file's hash.
Every page is labeled "Sample data".
"""

import hashlib
import uuid
from datetime import date

from fpdf import FPDF


def write_sample_certificate_pdf(
    student, title: str, issuer_name: str, out_dir: str | None = None
) -> tuple[str, str]:
    """Write a certificate PDF for `student`; returns (path, sha256)."""
    from ..config import get_settings

    settings = get_settings()
    directory = out_dir or settings.resolve(settings.uploads_dir)
    import os

    os.makedirs(directory, exist_ok=True)
    credential_id = f"ATT-{uuid.uuid4().hex[:8].upper()}"
    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(False)
    pdf.add_page()

    # Flat Attesta palette; no decoration.
    ink = (46, 31, 20)
    rust = (180, 69, 31)

    pdf.set_draw_color(*ink)
    pdf.set_line_width(0.6)
    pdf.rect(18, 18, 174, 261)

    pdf.set_text_color(*rust)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_xy(30, 40)
    pdf.cell(0, 12, "Certificate of Completion")

    pdf.set_text_color(*ink)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_xy(30, 62)
    pdf.multi_cell(150, 7, f"This is to certify that\n{student.full_name}")

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_xy(30, 86)
    pdf.multi_cell(150, 8, f"has successfully completed: {title}")

    pdf.set_font("Helvetica", "", 12)
    pdf.set_xy(30, 116)
    pdf.multi_cell(
        150,
        7,
        f"Awarded by: {issuer_name}\n"
        f"Issuer: {issuer_name} Registrar\n"
        f"Awarded to: {student.full_name}\n"
        f"Date issued: {date.today().isoformat()}\n"
        f"Credential ID: {credential_id}\n"
        f"Skills demonstrated: see course syllabus\n",
    )

    pdf.set_font("Helvetica", "", 10)
    pdf.set_xy(30, 250)
    pdf.multi_cell(
        150, 6, "Sample data - generated by Attesta for demonstration purposes."
    )

    path = os.path.join(directory, f"sample-{credential_id}.pdf")
    pdf.output(path)

    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return path, digest.hexdigest()


def write_sample_project_report_pdf(
    student, project_title: str, skills: list[str], out_dir: str | None = None
) -> tuple[str, str]:
    """A project report PDF for the demo student."""
    from ..config import get_settings

    settings = get_settings()
    directory = out_dir or settings.resolve(settings.uploads_dir)
    import os

    os.makedirs(directory, exist_ok=True)
    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(False)
    pdf.add_page()

    ink = (46, 31, 20)
    pdf.set_draw_color(*ink)
    pdf.set_line_width(0.6)
    pdf.rect(18, 18, 174, 261)

    pdf.set_text_color(*ink)
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_xy(30, 40)
    pdf.multi_cell(150, 10, f"Project Report: {project_title}")

    pdf.set_font("Helvetica", "", 12)
    pdf.set_xy(30, 70)
    skills_line = ", ".join(skills) if skills else "problem solving"
    pdf.multi_cell(
        150,
        7,
        f"Student: {student.full_name}\n"
        f"Project: {project_title}\n"
        f"Skills used: {skills_line}\n"
        f"Date: {date.today().isoformat()}\n\n"
        f"Summary: {student.full_name} completed the project '{project_title}' "
        f"using {skills_line}. The repository, dataset and notebook are "
        f"available on request for evaluation.",
    )
    pdf.set_font("Helvetica", "", 10)
    pdf.set_xy(30, 250)
    pdf.multi_cell(150, 6, "Sample data - generated by Attesta for demonstration purposes.")

    path = os.path.join(directory, f"project-{uuid.uuid4().hex[:8]}.pdf")
    pdf.output(path)

    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return path, digest.hexdigest()
