"""Storage adapter interface.

Local filesystem now; IPFS stub documents where decentralized storage would
plug in without touching any caller. Documents stay off-chain by design:
only the SHA-256 hash is anchored.
"""

import shutil
from pathlib import Path
from typing import BinaryIO


class StorageBackend:
    def save(self, key: str, content: BinaryIO) -> str:  # pragma: no cover - interface
        raise NotImplementedError

    def open(self, key: str) -> bytes:  # pragma: no cover - interface
        raise NotImplementedError

    def delete(self, key: str) -> None:  # pragma: no cover - interface
        raise NotImplementedError


class LocalStorage(StorageBackend):
    """Files under a configurable root (backend/uploads by default)."""

    def __init__(self, root: str):
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        # Refuse path traversal: keys are generated by the app, but be strict.
        path = (self.root / key).resolve()
        if self.root.resolve() not in path.parents:
            raise ValueError("invalid storage key")
        return path

    def save(self, key: str, content: BinaryIO) -> str:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "wb") as fh:
            shutil.copyfileobj(content, fh)
        return str(path)

    def open(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def delete(self, key: str) -> None:
        path = self._path(key)
        if path.exists():
            path.unlink()


class IpfsStorageStub(StorageBackend):
    """Placeholder for IPFS pinning (post-hackathon). Raises on use."""

    def save(self, key: str, content: BinaryIO) -> str:
        raise NotImplementedError("IPFS storage is not enabled in this build")

    def open(self, key: str) -> bytes:
        raise NotImplementedError("IPFS storage is not enabled in this build")

    def delete(self, key: str) -> None:
        raise NotImplementedError("IPFS storage is not enabled in this build")


_backend: StorageBackend | None = None


def get_storage() -> StorageBackend:
    from ..config import get_settings

    global _backend
    if _backend is None:
        settings = get_settings()
        _backend = LocalStorage(settings.resolve(settings.uploads_dir))
    return _backend
